AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ExecutionRoleArn:
    Type: String
  Image:
    Type: String
  ModelDataUrl:
    Type: String
  InitialInstanceCount:
    Type: String
  InstanceType:
    Type: String

Resources:

  Model:
    Type: AWS::SageMaker::Model
    Properties:
        ExecutionRoleArn:
          Ref: ExecutionRoleArn
        PrimaryContainer:
          Image:
            Ref: Image
          Mode: "SingleModel"
          ModelDataUrl:
            Ref: ModelDataUrl

  EndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialInstanceCount:
            Ref: InitialInstanceCount
          InstanceType:
            Ref: InstanceType
          ModelName:
            Fn::GetAtt: Model.ModelName
          VariantName: "iris"
          InitialVariantWeight: 1

  Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName